version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./back-fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/myapp

  vite-react:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vite-project:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
